### ISSUE TITLE
Distance Measurements are not counting a line segment

### ISSUE THREAD

**Issue by RyanWarne11** [magis-nc/esri-webappbuilder-widget-eDraw#15]
When selecting Show Measurements, the Distance measurement is not including the distance for one of the line segments in the polygon.  For example, if you Draw a rectangle and Show Measurements, the Area measurement is correct but the Distance measurement has only calculated 3 of the 4 sides.  Similarly with a Triangle, the Distance measurement will only calculate 2 of the 3 sides.  I noticed the same thing with a Polygon as well where I created a polygon with 7 line segments and the Distance measurement only calculated the first 6 line segments, so the Distance is incorrect for any polygon when comparing the same distance against the Measurement widget.

**Comment by jcornet** [comment]
Thanks for the modification.
The pull requests is merged
