### ISSUE TITLE
Typos and spelling errors

### ISSUE THREAD

**Issue by NatureMike** [magis-nc/esri-webappbuilder-widget-eDraw#2]
I have found a  few typos and spelling errors that I would like to correct.  In additional, people on my team think that it would be better to call the individual elements "graphics" instead of "drawings", while the whole stack of graphics that can be exported an imported should continue to be called "drawing".

**Comment by jcornet** [comment]
Hi mike,
You can fork and make a pull request with your modifications.
Your corrections are welcome !

**Comment by jcornet** [comment]
Hi Mike,
Any problem to fork and make a pull request ?

If you want, you can just modifiy the english traduction and send me the file back : 
https://raw.githubusercontent.com/magis-nc/esri-webappbuilder-widget-eDraw/master/nls/strings.js

**Comment by NatureMike** [comment]
Sorry, I was on a long vacation, but I will do that now.  Thanks!

**Comment by jcornet** [comment]
Thanks.
Closed with your pull request.
